### ISSUE TITLE
Incorrect bitshift?

### ISSUE THREAD

**Issue by g-berthiaume** [STMicroelectronics/ilps28qsw-pid#1]
Looking at the enum, it looks like this line should be ` >> 1`.

https://github.com/STMicroelectronics/ilps28qsw-pid/blob/9b15cc6d9739e9f8f0d75cf8f6fe47e095404636/ilps28qsw_reg.c#L477

**Comment by avisconti** [comment]
> Looking at the enum, it looks like this line should be ` >> 1`.

That's correct. Thanks for catching this up.

**Comment by avisconti** [comment]
Fixed by 3f4ef5b

**Comment by g-berthiaume** [comment]
no problem!
